 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     publish-windows64: 
         machine: 
            image: windows-server-2019-vs2019:stable     
    
     steps:
       - checkout
       - run: dotnet build
